### ISSUE TITLE
hi,there is a bug when saving the modules

### ISSUE THREAD

**Issue by leiyu2** [richardhahahaha/SpatialMaxFeatureMap#1]
There is a problem with the modules. When I save a network constains mfm modules, the saved model constains the train data(output and gradinput).  
So we need clear this data.Like this : 
model:get(2).modules:clearState()  
So I ask if we can  add a function to solve this problem.  Thx.

**Comment by richardhahahaha** [comment]
I add a method clearState to fix it.

**Comment by leiyu2** [comment]
thx
